### PR TITLE
HTML and CSS files Pull request

### PR DESCRIPTION
**Pull request by HunterX-7**
In this Pull Request, I:

- Created HTML-branch

- Followed GitHub flow.

- Added a descriptive and easy-to-understand README file

- Added a HTML file

- Added a CSS File

### CODE REVIEW

**Review by sajid-munawar — CHANGES_REQUESTED** [review]
# Changes Required 
 ### Hi @HunterX-7 ,
 Nice job, you are almost there.
 
 
 
 ## (Highlights) Good Points: 
 * Followed Github flow :heavy_check_mark:

 ## (Changes Required) Aspects to improve: 
 *  ### Please do the following:
- [x] Please kindly add a more descriptive PR title.
 See a demo below:

https://user-images.githubusercontent.com/52934128/176308229-e31b2c8d-110b-4823-a2a8-31c1b7d7c73d.mp4

- [x] I kindly suggest that you add a more descriptive PR title and description. 
## EXAMPLE
```
## Hello World
In this Pull Request, I:
- Created branches with different base branches.
- Followed GitHub flow.
- Added a descriptive and easy to understand README
- Added a HTML file
- Added a CSS File
- Added a h1 text of "Hello-World"
```


- [x] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

- [x] I suggest you kindly add a [README](https://github.com/microverseinc/readme-template) file to your repo, using the Microverse [template](https://github.com/microverseinc/readme-template) as this will give users detailed information about your project. please customize it as your details. Here is demo below

https://user-images.githubusercontent.com/52934128/176309876-98f49c4e-3e62-4edd-9bf3-51a66f48e2cd.mp4


 ## [Optional] suggestions:
 * Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding! :clap::clap::clap:**

> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @sajid-munawar in your question so I can receive the notification.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by fobadara — CHANGES_REQUESTED** [review]
# REQUIRES CHANGES ♻️ 
Hi @HunterX-7, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.


 ## Highlights
👍🏽 Linters is passing

 ## Required Changes ♻️
_Check the comments under the review._
There was no way I could use an inline comment for this suggestion so I added it here:
[REQUIRED] Kindly make your README professional by using the Microverse README template as suggested by the previous reviewer. You can click the link he gave you

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by HunterX-7** [comment]
Made the README more professional by using the Microverse README template as suggested by the previous reviewer.

**Review by Owusu-Desmond — APPROVED** [review]
Hi @HunterX-7 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
:heavy_check_mark: Good README file
:heavy_check_mark: Good PR.

## Optional suggestions

- [ ] I can see your readme file is well documented in the main branch but is not documented in this branch so next time, try to create a feature branch from for update branch.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
